apiVersion: v1
kind: Pod
metadata:
  name: caller
spec:
  containers:
    - name: caller-server
      image: docker.io/library/gocaller:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
