apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-tester
spec:
  containers:
    - name: rabbitmq-tester
      image: docker.io/library/rabbitmq-tester:latest
      # Just spin & wait forever
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
