apiVersion: batch/v1
kind: Job
metadata:
  name: queue-worker-1
spec:
  completions: 8
  parallelism: 2
  template:
    metadata:
      name: queue-worker-1
    spec:
      containers:
        - name: queue-worker
          image: docker.io/library/queue-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: QUEUE
              value: send-email
      restartPolicy: OnFailure
